### PR TITLE
Grizzly bear lesson

### PR DESCRIPTION
**Pull request by ateucher**
Could definitely be expanded, but the basics are there I think. @aammd hope you don't mind I'm submitting a PR from your fork. Seems a bit invasive!

### CODE REVIEW

**Comment by katieannemills** [comment]
Looks great guys! Is `explore_grizzly_data.html` generated from `explore_grizzly_data.Rmd`? Do we want both of them committed (especially seeing as the html is mostly encoded png)? Totally cool if we do want it - but then we need to remember to rebuild the html every time we change the rmd.

**Comment by ateucher** [comment]
Shades of the SWC conversation on the R material! The html automatically gets built at the same time as the md (the Rmd is the source for both). Having the md is nice because it renders with the output on github, but I am ambivalent about keeping the html.... @aammd what do you think?

**Comment by katieannemills** [comment]
OK - no need to split hairs too hard here; this is great work, I'm just going to merge it all in. Thanks!

**Comment by ateucher** [comment]
Great!

**Pull request merged**
